# Dataset modification

add months column
add hour column
cluster station
categorize wind direction

In [1]:
import pandas as pd

path='C:\\Users\\olivi\\OneDrive\\Documents\\McGill MMA\\Fall 2023\\Data mining (INSY662)\\Project\\Lyft data\\'
df = pd.read_csv(path+"complete_dataset.csv", sep=',')

df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,wdir,wspd,wpgt,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,339.0,7.6,NaN,1024.3,NaN,Thursday,0,9.833333,2.193119,13.381745
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,109.0,7.2,NaN,1022.2,NaN,Saturday,0,11.133333,2.193119,11.819206
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,220.0,14.8,NaN,1014.8,NaN,Friday,0,20.633333,1.997210,5.807719
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,312.0,8.6,NaN,1021.4,NaN,Monday,0,34.666667,6.153860,10.650911
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,48.0,3.6,NaN,1024.8,NaN,Friday,0,11.550000,1.246058,6.473028

### Add months

In [2]:
import calendar

# Convert the 'started_at' column to datetime, if it's not already
df['started_at'] = pd.to_datetime(df['started_at'])

# Create a new 'month' column by mapping the month number to month names
df['month'] = df['started_at'].dt.month.map(lambda x: calendar.month_name[x])

df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,wspd,wpgt,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed,month
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,7.6,NaN,1024.3,NaN,Thursday,0,9.833333,2.193119,13.381745,January
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,7.2,NaN,1022.2,NaN,Saturday,0,11.133333,2.193119,11.819206,January
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,14.8,NaN,1014.8,NaN,Friday,0,20.633333,1.997210,5.807719,January
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,8.6,NaN,1021.4,NaN,Monday,0,34.666667,6.153860,10.650911,January
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,3.6,NaN,1024.8,NaN,Friday,0,11.550000,1.246058,6.473028,January

### Add hours

In [3]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['hour'] = df['started_at'].dt.hour

df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,wpgt,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed,month,hour
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,NaN,1024.3,NaN,Thursday,0,9.833333,2.193119,13.381745,January,19
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,NaN,1022.2,NaN,Saturday,0,11.133333,2.193119,11.819206,January,15
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,NaN,1014.8,NaN,Friday,0,20.633333,1.997210,5.807719,January,20
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,NaN,1021.4,NaN,Monday,0,34.666667,6.153860,10.650911,January,16
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,NaN,1024.8,NaN,Friday,0,11.550000,1.246058,6.473028,January,17

### Add wind direction categories

In [6]:
# Define a function to categorize wind direction into four cardinal directions
def categorize_wind_direction(degrees):
    if (315 <= degrees < 360) or (0 <= degrees < 45):
        return 'North'
    elif 45 <= degrees < 135:
        return 'East'
    elif 135 <= degrees < 225:
        return 'South'
    elif 225 <= degrees < 315:
        return 'West'

# Create a new column 'wind_direction_category' based on the 'wdir' column
df['wind_direction'] = df['wdir'].apply(categorize_wind_direction)

df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed,month,hour,wind_direction
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,1024.3,NaN,Thursday,0,9.833333,2.193119,13.381745,January,19,North
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,1022.2,NaN,Saturday,0,11.133333,2.193119,11.819206,January,15,East
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,1014.8,NaN,Friday,0,20.633333,1.997210,5.807719,January,20,South
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,1021.4,NaN,Monday,0,34.666667,6.153860,10.650911,January,16,West
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,1024.8,NaN,Friday,0,11.550000,1.246058,6.473028,January,17,East

### Clustering the stations

In [10]:
#start

# Select the relevant columns for stations
station_columns = ['start_station_id', 'start_station_name', 'start_lat', 'start_lng']

# Drop duplicates and keep the first occurrence
start_stations_df = df[station_columns].drop_duplicates(subset=['start_station_id'])

# Rename the columns for consistency
start_stations_df = start_stations_df.rename(columns={
    'start_station_id': 'station_id',
    'start_station_name': 'station_name',
    'start_lat': 'station_lat',
    'start_lng': 'station_lng'
})

# Reset the index to have consecutive integer indices
start_stations_df = start_stations_df.reset_index(drop=True)

# Display the resulting DataFrame
start_stations_df

################################################################

#end
# Select the relevant columns for stations
station_columns = ['end_station_id', 'end_station_name', 'end_lat', 'end_lng']

# Drop duplicates and keep the first occurrence
end_stations_df = df[station_columns].drop_duplicates(subset=['end_station_id'])

# Rename the columns for consistency
end_stations_df = end_stations_df.rename(columns={
    'end_station_id': 'station_id',
    'end_station_name': 'station_name',
    'end_lat': 'station_lat',
    'end_lng': 'station_lng'
})

# Reset the index to have consecutive integer indices
end_stations_df = end_stations_df.reset_index(drop=True)

################################################################

# Perform an outer merge on station_id to find stations unique to either "start" or "end"
unique_stations_df = pd.merge(start_stations_df, end_stations_df, on='station_id', how='outer', indicator=True)

# Filter for rows where one of the station IDs is missing
unique_start_stations_df = unique_stations_df[unique_stations_df['_merge'] == 'left_only']
unique_end_stations_df = unique_stations_df[unique_stations_df['_merge'] == 'right_only']

# Drop the '_merge' column
unique_start_stations_df = unique_start_stations_df.drop('_merge', axis=1)
unique_end_stations_df = unique_end_stations_df.drop('_merge', axis=1)

# Display the unique start stations
print("Unique Start Stations:")
print(unique_start_stations_df)

# Display the unique end stations
print("\nUnique End Stations:")
print(unique_end_stations_df)

Unique Start Stations:
Empty DataFrame
Columns: [station_id, station_name_x, station_lat_x, station_lng_x, station_name_y, station_lat_y, station_lng_y]
Index: []

Unique End Stations:
          station_id station_name_x  station_lat_x  station_lng_x  \
509   San Jose Depot            NaN            NaN            NaN
510  EB Test Station            NaN            NaN            NaN

      station_name_y  station_lat_y  station_lng_y
509   San Jose Depot      37.344018    -121.915063
510  EB Test Station       0.000000       0.000000

San Jose Depot is only used once and EB Test station is only used twice (and has fake coordinates) so we can forget these observations and only use the station in "start" for clustering

In [11]:
# Select the relevant columns for stations
station_columns = ['start_station_id', 'start_station_name', 'start_lat', 'start_lng']

# Drop duplicates and keep the first occurrence
stations_df = df[station_columns].drop_duplicates(subset=['start_station_id'])

# Rename the columns for consistency
stations_df = stations_df.rename(columns={
    'start_station_id': 'station_id',
    'start_station_name': 'station_name',
    'start_lat': 'station_lat',
    'start_lng': 'station_lng'
})

# Reset the index to have consecutive integer indices
stations_df = stations_df.reset_index(drop=True)

# Display the resulting DataFrame
stations_df

,station_id,station_name,station_lat,station_lng
0,SF-E22,Washington St at Van Ness Ave,37.792980,-122.423302
1,SF-N21,17th St at Dolores St,37.763015,-122.426497
2,OK-I9,El Embarcadero at Grand Ave,37.808715,-122.249251
3,BK-E10,Haste St at College Ave,37.866418,-122.253799
4,SF-O21,Mission Dolores Park,37.761376,-122.426486
...,...,...,...,...
504,SF-F30-3,Folsom St at Main St,37.788991,-122.392255
505,SF-C20-2,Webster St at Union St,37.797387,-122.433981
506,SpecialEventTempStation,Hardly Strictly Bluegrass,37.770769,-122.479098
507,SF-F17-1,Clay St at Lyon St,37.789417,-122.445156
508,SF-L24-2,Bryant St at 15th St,37.767100,-122.410662

### Let's first visualize where are the stations on the San Franciso map

In [30]:
# pip install folium

import folium

# Assuming you have the 'stations_df' DataFrame with columns 'station_lat', 'station_lng', and 'station_name'

# Create a map centered around San Francisco
m = folium.Map(location=[37.7749, -122.4194], zoom_start=12)

# Add markers for each station
for index, row in stations_df.iterrows():
    folium.Marker(
        location=[row['station_lat'], row['station_lng']],
        popup=row['station_name']
    ).add_to(m)

# Display the map
m.save('bike_stations_map.html')

We can see there is 3 clear clusters

### Try 3 clusters

In [35]:
# for 3 clusters

import folium
from sklearn.cluster import KMeans
import pandas as pd

# Assuming you have the 'stations_df' DataFrame with columns 'station_lat', 'station_lng', and 'station_name'

# Perform K-Means clustering with 3 clusters
n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(stations_df[['station_lat', 'station_lng']])

# Add cluster labels to the DataFrame
stations_df['cluster'] = kmeans.labels_

# Create a map centered around San Francisco
m = folium.Map(location=[37.7749, -122.4194], zoom_start=12)

# Define a list of colors for clusters
cluster_colors = ['red', 'blue', 'green']

# Add markers for each station with cluster-specific colors
for index, row in stations_df.iterrows():
    cluster_color = cluster_colors[row['cluster']]
    folium.CircleMarker(
        location=[row['station_lat'], row['station_lng']],
        radius=5,
        color=cluster_color,
        fill=True,
        fill_color=cluster_color,
        fill_opacity=0.7,
        popup=row['station_name']
    ).add_to(m)

# Display the map
m.save('clustered_bike_stations_map.html')

c:\Users\olivi\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\olivi\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

But 3 clusters is not enough as the region is very big. We will try more clusters as it's better to have a bit more groups for our project.

### Try 20 clusters

In [17]:
import folium
from sklearn.cluster import KMeans
import pandas as pd
import random

# Assuming you have the 'stations_df' DataFrame with columns 'station_lat', 'station_lng', and 'station_name'

# Perform K-Means clustering with 20 clusters
n_clusters = 20
kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(stations_df[['station_lat', 'station_lng']])

# Add cluster labels to the DataFrame
stations_df['cluster'] = kmeans.labels_

# Create a map centered around San Francisco
m = folium.Map(location=[37.7749, -122.4194], zoom_start=12)

# Generate random colors for clusters
cluster_colors = ['#{:02x}{:02x}{:02x}'.format(random.randint(0, 255), random.randint(0, 255), random.randint(0, 255) ) for _ in range(n_clusters)]

# Add markers for each station with cluster-specific colors
for index, row in stations_df.iterrows():
    cluster_color = cluster_colors[row['cluster']]
    folium.CircleMarker(
        location=[row['station_lat'], row['station_lng']],
        radius=5,
        color=cluster_color,
        fill=True,
        fill_color=cluster_color,
        fill_opacity=0.7,
        popup=row['station_name']
    ).add_to(m)

# Display the map
m.save('clustered_bike_stations_map_20_clusters.html')

c:\Users\olivi\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\olivi\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

In [25]:
# Merge the cluster labels for start stations
df = df.merge(stations_df[['station_id', 'cluster']], left_on='start_station_id', right_on='station_id', how='left')

# Rename the 'cluster' column to 'start_station_cluster'
df = df.rename(columns={'cluster': 'start_station_cluster'})

# Merge the cluster labels for end stations
df = df.merge(stations_df[['station_id', 'cluster']], left_on='end_station_id', right_on='station_id', how='left')

# Rename the 'cluster' column to 'end_station_cluster'
df = df.rename(columns={'cluster': 'end_station_cluster'})

In [35]:
# Drop rows with NA values in the specified columns
df = df.dropna(subset=['start_station_cluster', 'end_station_cluster'])

# Cast the new columns to integer type
df['start_station_cluster'] = df['start_station_cluster'].astype(int)
df['end_station_cluster'] = df['end_station_cluster'].astype(int)

# Drop the specified columns
df = df.drop(['station_id_x', 'station_id_y'], axis=1)

In [36]:
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed,month,hour,wind_direction,start_station_cluster,end_station_cluster
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,Thursday,0,9.833333,2.193119,13.381745,January,19,North,18,16
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,Saturday,0,11.133333,2.193119,11.819206,January,15,East,18,16
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,Friday,0,20.633333,1.997210,5.807719,January,20,South,3,7
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,Monday,0,34.666667,6.153860,10.650911,January,16,West,9,10
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,Friday,0,11.550000,1.246058,6.473028,January,17,East,3,3

In [37]:
# Save the combined dataframe to a new CSV file
path = r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\complete_dataset_V2.csv'
df.to_csv(path, index=False)