In [1]:
import pandas as pd

path='C:\\Users\\olivi\\OneDrive\\Documents\\McGill MMA\\Fall 2023\\Data mining (INSY662)\\Project\\Lyft data\\'
df = pd.read_csv(path+"complete_dataset_V2.csv", sep=',')

df.head(5)

C:\Users\olivi\AppData\Local\Temp\ipykernel_31016\1114135126.py:4: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path+"complete_dataset_V2.csv", sep=',')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed,month,hour,wind_direction,start_station_cluster,end_station_cluster
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,Thursday,0,9.833333,2.193119,13.381745,January,19,North,18,16
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,Saturday,0,11.133333,2.193119,11.819206,January,15,East,18,16
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,Friday,0,20.633333,1.997210,5.807719,January,20,South,3,7
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,Monday,0,34.666667,6.153860,10.650911,January,16,West,9,10
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,Friday,0,11.550000,1.246058,6.473028,January,17,East,3,3

In [6]:
import pandas as pd

# Assuming your original DataFrame is named 'df'
# Replace these column names with the actual column names from your dataset
columns_to_select = ['started_at', 'start_station_cluster', 'rideable_type']

# Select relevant columns
selected_data = df[columns_to_select]

# Convert 'started_at' to datetime format if it's not already
selected_data['started_at'] = pd.to_datetime(selected_data['started_at'])

# Replace 'docked_bike' with 'classic_bike' in the 'rideable_type' column
selected_data['rideable_type'] = selected_data['rideable_type'].replace({'docked_bike': 'classic_bike'})

# Create a new column for the date without time
selected_data['date'] = selected_data['started_at'].dt.date

# Group by 'date', 'start_station_cluster', and 'rideable_type', then count the number of trips
demand_df = selected_data.groupby(['date', 'start_station_cluster', 'rideable_type']).size().reset_index(name='trip_count')

# Display the resulting DataFrame
demand_df

C:\Users\olivi\AppData\Local\Temp\ipykernel_31016\4030012193.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['started_at'] = pd.to_datetime(selected_data['started_at'])
C:\Users\olivi\AppData\Local\Temp\ipykernel_31016\4030012193.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['rideable_type'] = selected_data['rideable_type'].replace({'docked_bike': 'classic_bike'})
C:\Users\olivi\AppData\Local\Temp\ipykernel_31016\4030012193.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['date'] = selected_data['started_at'].dt.date

             date  start_station_cluster  rideable_type  trip_count
0      2022-01-01                      0   classic_bike          94
1      2022-01-01                      0  electric_bike         196
2      2022-01-01                      1   classic_bike          11
3      2022-01-01                      1  electric_bike           8
4      2022-01-01                      2   classic_bike          37
...           ...                    ...            ...         ...
12299  2022-12-31                     17  electric_bike         189
12300  2022-12-31                     18   classic_bike          13
12301  2022-12-31                     18  electric_bike          46
12302  2022-12-31                     19   classic_bike           9
12303  2022-12-31                     19  electric_bike           4

[12304 rows x 4 columns]

In [8]:
# Save
path = r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\dataset_demand.csv'
demand_df.to_csv(path, index=False)