### Combine the Lyft csv files

In [3]:
import pandas as pd

# Define the file paths for your CSV files
file_paths = [
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202201-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202202-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202203-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202204-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202205-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202206-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202207-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202208-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202209-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202210-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202211-baywheels-tripdata.csv',
    r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\202212-baywheels-tripdata.csv'
]

# Read the CSV files into dataframes and combine them
combined_lyft = pd.concat([pd.read_csv(file) for file in file_paths], ignore_index=True)

### Add the weather attributes

In [5]:
import pandas as pd

# Define the file paths for your CSV files
#combined_lyft_path = r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\combined_lyft.csv'
weather_path = r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\weather.csv'

# Read the CSV files into dataframes
#combined_lyft = pd.read_csv(combined_lyft_path)
weather = pd.read_csv(weather_path)

# Perform a left join on the "start_time" column in combined_data and the "date" column in weather
lyft_weather = pd.merge(combined_lyft, weather, left_on=combined_lyft['started_at'].str[:10], right_on=weather['date'], how='left')

# Drop the redundant 'date' column that comes from the 'weather' dataset
lyft_weather.drop(columns='date', inplace=True)

# If it created a 'key_0' column : drop it
lyft_weather.drop(columns='key_0', inplace=True)

### Add the day of the week the trip was (Monday, Tuesday, Wednesday...)

In [6]:
lyft_weather['started_at'] = pd.to_datetime(lyft_weather['started_at'])
lyft_weather['day_of_the_week'] = lyft_weather['started_at'].dt.strftime('%A')

### Add the Holidays

In [7]:
# pip install holidays

In [8]:
import holidays

# Create a list of US holidays
us_holidays = holidays.US()

# New Year's Day (January 1)
# Martin Luther King Jr. Day (third Monday in January)
# Presidents' Day (third Monday in February)
# Memorial Day (last Monday in May)
# Independence Day (July 4)
# Labor Day (first Monday in September)
# Columbus Day (second Monday in October)
# Veterans Day (November 11)
# Thanksgiving Day (fourth Thursday in November)
# Christmas Day (December 25)

# Define a function to check if a date is a US holiday
def is_us_holiday(date):
    return date in us_holidays

# Apply the function to create the "Holiday" column
lyft_weather['Holiday'] = lyft_weather['started_at'].apply(is_us_holiday).astype(int)

lyft_weather_holiday = lyft_weather

# Now, lyft_weather['Holiday'] will contain binary values (1 for US holidays and 0 for non-holidays)

In [9]:
# Sort the DataFrame by the "started_at" column in ascending order
test = lyft_weather_holiday.sort_values(by='started_at')
test.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,day_of_the_week,Holiday
113260,C35E15A6FF9D244C,docked_bike,2022-01-01 00:03:19,2022-01-01 00:16:13,Powell St BART Station (Market St at 5th St),SF-H26,Grove St at Gough St,SF-J22-2,37.783899,-122.408445,...,11.1,0.0,NaN,8.0,5.0,NaN,1022.1,NaN,Saturday,1
134037,B466BE17E360AFD0,electric_bike,2022-01-01 00:03:58,2022-01-01 00:12:26,NaN,NaN,Berry St at 4th St,SF-K29-1,37.800000,-122.390000,...,11.1,0.0,NaN,8.0,5.0,NaN,1022.1,NaN,Saturday,1
146783,68EF48E530360614,electric_bike,2022-01-01 00:04:00,2022-01-01 00:23:44,1st St at Folsom St,SF-G29-2,NaN,NaN,37.787124,-122.394375,...,11.1,0.0,NaN,8.0,5.0,NaN,1022.1,NaN,Saturday,1
113304,6B651E341F8CA30F,docked_bike,2022-01-01 00:04:10,2022-01-01 00:16:03,Powell St BART Station (Market St at 5th St),SF-H26,Grove St at Gough St,SF-J22-2,37.783899,-122.408445,...,11.1,0.0,NaN,8.0,5.0,NaN,1022.1,NaN,Saturday,1
46423,BDB937946C36744B,electric_bike,2022-01-01 00:04:18,2022-01-01 00:19:10,Washington St at Kearny St,SF-D27,4th St at 16th St,SF-M30,37.795338,-122.404773,...,11.1,0.0,NaN,8.0,5.0,NaN,1022.1,NaN,Saturday,1

### Add time elapsed between start and end

In [11]:
# Convert the 'started_at' and 'ended_at' columns to datetime objects
lyft_weather_holiday['started_at'] = pd.to_datetime(lyft_weather_holiday['started_at'])
lyft_weather_holiday['ended_at'] = pd.to_datetime(lyft_weather_holiday['ended_at'])

# Calculate the time difference in minutes and store it in a new column 'trip_time'
lyft_weather_holiday['trip_time'] = (lyft_weather_holiday['ended_at'] - lyft_weather_holiday['started_at']).dt.total_seconds() / 60

### Add distance traveled between start and end

In [12]:
import pandas as pd
import numpy as np

# Define a function to calculate the Haversine distance between two sets of coordinates
def haversine_distance(lat1, lon1, lat2, lon2):
    # Radius of the Earth in kilometers
    R = 6371.0

    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = np.radians([lat1, lon1, lat2, lon2])

    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    # Calculate the distance
    distance = R * c
    return distance

# Assuming your DataFrame is named lyft_weather_holiday

# Calculate the distance traveled using the Haversine formula and store it in a new column 'distance_traveled'
lyft_weather_holiday['distance_traveled'] = lyft_weather_holiday.apply(
    lambda row: haversine_distance(row['start_lat'], row['start_lng'], row['end_lat'], row['end_lng']), axis=1)

In [13]:
lyft_weather_holiday.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,snow,wdir,wspd,wpgt,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,NaN,339.0,7.6,NaN,1024.3,NaN,Thursday,0,9.833333,2.193119
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,NaN,109.0,7.2,NaN,1022.2,NaN,Saturday,0,11.133333,2.193119
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,NaN,220.0,14.8,NaN,1014.8,NaN,Friday,0,20.633333,1.997210
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,NaN,312.0,8.6,NaN,1021.4,NaN,Monday,0,34.666667,6.153860
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,NaN,48.0,3.6,NaN,1024.8,NaN,Friday,0,11.550000,1.246058

### Add average speed

In [14]:
# Calculate the average speed in km/h and store it in a new column 'average_speed'
# lyft_weather_holiday['average_speed'] = (lyft_weather_holiday['distance_traveled'] / (lyft_weather_holiday['trip_time'] / 60)).fillna(0)
# lyft_weather_holiday.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,wdir,wspd,wpgt,pres,tsun,day_of_the_week,Holiday,trip_time,distance_traveled,average_speed
0,0DD008BC62836D27,classic_bike,2022-01-13 19:12:23,2022-01-13 19:22:13,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,339.0,7.6,NaN,1024.3,NaN,Thursday,0,9.833333,2.193119,13.381745
1,BE9F5C77F1BE0FBF,classic_bike,2022-01-15 15:58:55,2022-01-15 16:10:03,Washington St at Van Ness Ave,SF-E22,Natoma St at New Montgomery St,SF-G28-2,37.792980,-122.423302,...,109.0,7.2,NaN,1022.2,NaN,Saturday,0,11.133333,2.193119,11.819206
2,F0826402062D5A44,classic_bike,2022-01-07 20:34:47,2022-01-07 20:55:25,17th St at Dolores St,SF-N21,Scott St at Golden Gate Ave,SF-I19,37.763015,-122.426497,...,220.0,14.8,NaN,1014.8,NaN,Friday,0,20.633333,1.997210,5.807719
3,EE9A8BB189061CFD,classic_bike,2022-01-31 16:38:25,2022-01-31 17:13:05,El Embarcadero at Grand Ave,OK-I9,Ninth St at Heinz Ave,BK-H3,37.808715,-122.249251,...,312.0,8.6,NaN,1021.4,NaN,Monday,0,34.666667,6.153860,10.650911
4,772A8B545A8525C0,classic_bike,2022-01-28 17:28:22,2022-01-28 17:39:55,17th St at Dolores St,SF-N21,Octavia Blvd at Page St,SF-J22-1,37.763015,-122.426497,...,48.0,3.6,NaN,1024.8,NaN,Friday,0,11.550000,1.246058,6.473028

### Save as a new csv file

In [15]:
# Save the combined dataframe to a new CSV file
path = r'C:\Users\olivi\OneDrive\Documents\McGill MMA\Fall 2023\Data mining (INSY662)\Project\Lyft data\complete_dataset.csv'
lyft_weather_holiday.to_csv(path, index=False)